version: '3.8' # Docker compose version
services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile #  Dockerfile
    ports:
      - "8080:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    restart: always 

